# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'worker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for worker

  target 'workerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'workerUITests' do
    # Pods for testing
	pod 'Cucumberish'
  end

end